services:
  api:
    build: .
    container_name: sakila_videos_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sakila_videos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sakila
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      TZ: "UTC"
    command: --log-bin-trust-function-creators=1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
